### ISSUE TITLE
Remove token from README

### ISSUE THREAD

**Issue by nateraw** [archinetai/audio-diffusion-pytorch-trainer#1]
You have your hugging face token chillin in your readme right now. Maybe better to explain folks should:

1. Create a Hugging Face account if they don't already have one
2. Accept the terms of the [common voice dataset](https://huggingface.co/datasets/mozilla-foundation/common_voice_8_0) (link is to specific version, but they'd have to do it for whatever version they're using)
3. Use `huggingface-cli login` or `huggingface_hub.notebook_login()` on their machine to authenticate with Hugging Face.

Edit, whoops I see its random 😅 will close this and leave it up to you if you wanna add the above

**Comment by flavioschneider** [comment]
I've added a FAQ section with the explanation :)
