### ISSUE TITLE
Training following pip --upgrade of packages

### ISSUE THREAD

**Issue by rlabs-oss** [archinetai/audio-diffusion-pytorch-trainer#3]
internal/utils.py", line 648, in _locate
    raise ImportError(
ImportError: Error loading 'audio_diffusion_pytorch.VDistribution':
ModuleNotFoundError("No module named 'audio_diffusion_pytorch.VDistribution'")
Are you sure that 'VDistribution' is importable from module 'audio_diffusion_pytorch'?

From where is the VDistribution installed from or used?

**Comment by rlabs-oss** [comment]
┏━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃   ┃ Name                ┃ Type                ┃ Params ┃
┡━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0 │ model               │ AudioDiffusionModel │  736 M │
│ 1 │ model.unet          │ UNet1d              │  736 M │
│ 2 │ model.diffusion     │ VDiffusion          │  736 M │
│ 3 │ model_ema           │ EMA                 │  1.5 B │
│ 4 │ model_ema.ema_model │ AudioDiffusionModel │  736 M │
└───┴─────────────────────┴─────────────────────┴────────┘
Trainable params: 736 M                                                                                                         
Non-trainable params: 736 M                                                                                                     
Total params: 1.5 B                                                                                                             
Total estimated model params size (MB): 5.9 K 

followed by:

    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

Any idea why the #params is so low followed by 0 samples error?

**Comment by ModeratePrawn** [comment]
@rlabs-oss What was the solution for this issue? I have upgraded and am running into the same.

**Comment by flavioschneider** [comment]
You have to use `audio_diffusion_pytorch.VKDistribution` instead, I still have to delete those old experiments that are not up to date
