### ISSUE TITLE
Error Locating Target

### ISSUE THREAD

**Issue by ModeratePrawn** [archinetai/audio-diffusion-pytorch-trainer#4]
Hello,

I upgraded the trainer and audio diffusion to the latest releases. I am now getting this error when trying to run experiments:

[2022-10-19 09:47:41,538][main][INFO] - Instantiating model <main.module_base.Model>.
Error executing job with overrides: ['exp=base_youtube_l_3.yaml']
Error locating target 'audio_diffusion_pytorch.VDistribution', see chained exception above.
full_key: model.model.diffusion_sigma_distribution

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

I deleted the conda environment and reinstalled all of the requirements from scratch, and I am still getting the above. Any help would be appreciated.

Thanks,
MP

**Comment by flavioschneider** [comment]
You have to use `diffusion_type='vk'` with `audio_diffusion_pytorch.VKDistribution`, I still have to delete those old experiments that are not up to date

**Comment by flavioschneider** [comment]
The old experiments have been archived and the new updated, you should be able to run the current version.

**Comment by ModeratePrawn** [comment]
Seems to be working now! Thank you!

[2022-10-19 12:41:18,081][__main__][INFO] - Logging hyperparameters!
[2022-10-19 12:41:18,122][__main__][INFO] - Starting training.
┏━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃   ┃ Name                ┃ Type                ┃ Params ┃
┡━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0 │ model               │ AudioDiffusionModel │  640 M │
│ 1 │ model.unet          │ UNet1d              │  640 M │
│ 2 │ model.diffusion     │ VDiffusion          │  640 M │
│ 3 │ model_ema           │ EMA                 │  1.3 B │
│ 4 │ model_ema.ema_model │ AudioDiffusionModel │  640 M │
└───┴─────────────────────┴─────────────────────┴────────┘
Trainable params: 640 M                                                                                                                                                                                                                     
Non-trainable params: 640 M                                                                                                                                                                                                                 
Total params: 1.3 B                                                                                                                                                                                                                         
Total estimated model params size (MB): 5.1 K
