### ISSUE TITLE
WAVdatasets, path location and DIR_DATA=/somewhere

### ISSUE THREAD

**Issue by twobob** [archinetai/audio-diffusion-pytorch-trainer#8]
Might it be possible express an absolute path on a wavdataset in the declaration. 
The DATADIR does not operate how I imagined.

What I expected :   DIR_DATA=/data  would be treated as an absolute path. Or worst case a relative path from the execution directory and placing .Wav or .Flac in a the specified directory would be enough to get the model to find them.

What actually happens: DIR_DATA=/data is treated as a relative path, based on the execution location. Placing wav or flac files in the location results in a zero length error.

**Comment by flavioschneider** [comment]
Yes it's possible! In the `config.yaml` change this:
```yaml
data_dir: ${work_dir}${oc.env:DIR_DATA}
```
To this

```yaml
data_dir: ${oc.env:DIR_DATA}
```

You can alternatively create a symlink to your data path from the relative data path https://linuxhint.com/symlink-a-directory-in-linux
